# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 07:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='modify',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
