# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 00:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modifieddate',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 8, 0, 28, 23, 230236, tzinfo=utc), verbose_name='修改日期'),
        ),
    ]
