# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170705_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='modify',
            field=models.DateTimeField(auto_now=True, verbose_name='最后修改日期'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='pubdate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='保存日期'),
        ),
    ]
