# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 10:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170705_0710'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='modify',
            new_name='modifieddate',
        ),
    ]
